// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// getEntities
IntegerVector getEntities(NumericMatrix ma);
RcppExport SEXP _gen3sis_getEntities(SEXP maSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type ma(maSEXP);
    rcpp_result_gen = Rcpp::wrap(getEntities(ma));
    return rcpp_result_gen;
END_RCPP
}
// epsN
IntegerVector epsN(NumericVector LP, double d1);
RcppExport SEXP _gen3sis_epsN(SEXP LPSEXP, SEXP d1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type LP(LPSEXP);
    Rcpp::traits::input_parameter< double >::type d1(d1SEXP);
    rcpp_result_gen = Rcpp::wrap(epsN(LP, d1));
    return rcpp_result_gen;
END_RCPP
}
// conc
IntegerVector conc(IntegerVector x, IntegerVector y);
RcppExport SEXP _gen3sis_conc(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(conc(x, y));
    return rcpp_result_gen;
END_RCPP
}
// is_any_f
bool is_any_f(LogicalVector x);
RcppExport SEXP _gen3sis_is_any_f(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(is_any_f(x));
    return rcpp_result_gen;
END_RCPP
}
// Tdbscan
IntegerVector Tdbscan(NumericMatrix D, double d1, double minPts);
RcppExport SEXP _gen3sis_Tdbscan(SEXP DSEXP, SEXP d1SEXP, SEXP minPtsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type D(DSEXP);
    Rcpp::traits::input_parameter< double >::type d1(d1SEXP);
    Rcpp::traits::input_parameter< double >::type minPts(minPtsSEXP);
    rcpp_result_gen = Rcpp::wrap(Tdbscan(D, d1, minPts));
    return rcpp_result_gen;
END_RCPP
}
// Tdbscan_variable
IntegerVector Tdbscan_variable(NumericMatrix D, NumericVector distances, double minPts);
RcppExport SEXP _gen3sis_Tdbscan_variable(SEXP DSEXP, SEXP distancesSEXP, SEXP minPtsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type D(DSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type distances(distancesSEXP);
    Rcpp::traits::input_parameter< double >::type minPts(minPtsSEXP);
    rcpp_result_gen = Rcpp::wrap(Tdbscan_variable(D, distances, minPts));
    return rcpp_result_gen;
END_RCPP
}
// get_distance_matrix
Rcpp::NumericMatrix get_distance_matrix(const IntegerVector habitable_cells, const int num_cells, const IntegerVector dist_p, const IntegerVector dist_i, const NumericVector dist_x, const double max_distance);
RcppExport SEXP _gen3sis_get_distance_matrix(SEXP habitable_cellsSEXP, SEXP num_cellsSEXP, SEXP dist_pSEXP, SEXP dist_iSEXP, SEXP dist_xSEXP, SEXP max_distanceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector >::type habitable_cells(habitable_cellsSEXP);
    Rcpp::traits::input_parameter< const int >::type num_cells(num_cellsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type dist_p(dist_pSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type dist_i(dist_iSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type dist_x(dist_xSEXP);
    Rcpp::traits::input_parameter< const double >::type max_distance(max_distanceSEXP);
    rcpp_result_gen = Rcpp::wrap(get_distance_matrix(habitable_cells, num_cells, dist_p, dist_i, dist_x, max_distance));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gen3sis_getEntities", (DL_FUNC) &_gen3sis_getEntities, 1},
    {"_gen3sis_epsN", (DL_FUNC) &_gen3sis_epsN, 2},
    {"_gen3sis_conc", (DL_FUNC) &_gen3sis_conc, 2},
    {"_gen3sis_is_any_f", (DL_FUNC) &_gen3sis_is_any_f, 1},
    {"_gen3sis_Tdbscan", (DL_FUNC) &_gen3sis_Tdbscan, 3},
    {"_gen3sis_Tdbscan_variable", (DL_FUNC) &_gen3sis_Tdbscan_variable, 3},
    {"_gen3sis_get_distance_matrix", (DL_FUNC) &_gen3sis_get_distance_matrix, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_gen3sis(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
