# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

integrateModelVectorized <- function(init, g_in, c_in, l_in, t0, t1, dt) {
    .Call(`_gen3sis_integrateModelVectorized`, init, g_in, c_in, l_in, t0, t1, dt)
}

integrateModel <- function(init, r, a, t0, t1, dt) {
    .Call(`_gen3sis_integrateModel`, init, r, a, t0, t1, dt)
}

getEntities <- function(ma) {
    .Call(`_gen3sis_getEntities`, ma)
}

epsN <- function(LP, d1) {
    .Call(`_gen3sis_epsN`, LP, d1)
}

conc <- function(x, y) {
    .Call(`_gen3sis_conc`, x, y)
}

is_any_f <- function(x) {
    .Call(`_gen3sis_is_any_f`, x)
}

Tdbscan <- function(D, d1, minPts) {
    .Call(`_gen3sis_Tdbscan`, D, d1, minPts)
}

Tdbscan_variable <- function(D, distances, minPts) {
    .Call(`_gen3sis_Tdbscan_variable`, D, distances, minPts)
}

AllopatryKernel <- function(dist1, ds, Speciesj) {
    .Call(`_gen3sis_AllopatryKernel`, dist1, ds, Speciesj)
}

SympatryKernel <- function(Speciesj, p, NbAllo) {
    .Call(`_gen3sis_SympatryKernel`, Speciesj, p, NbAllo)
}

DispersionKernel <- function(dist2, d, Speciesj) {
    .Call(`_gen3sis_DispersionKernel`, dist2, d, Speciesj)
}

SpDiv <- function(ds, d, p, MatrixSpecies, dist1, dist2, SpMax) {
    .Call(`_gen3sis_SpDiv`, ds, d, p, MatrixSpecies, dist1, dist2, SpMax)
}

get_distance_matrix <- function(habitable_cells, num_cells, dist_p, dist_i, dist_x, max_distance) {
    .Call(`_gen3sis_get_distance_matrix`, habitable_cells, num_cells, dist_p, dist_i, dist_x, max_distance)
}

